export const QUERY_KEYS = {
  STRATEGIES: "strategies",
  STRATEGIES_TAGS: "strategiesTags",
  STRATEGY: "strategy",
  USER: "user",
  CHAT: "chat",
  CONVERSATIONS: "conversations",
  CONVERSATION: "conversation",
  AI_MODELS: "aiModels",
  AI_CHAT_TEMPLATES: "ai-chat-templates",
  PLANS: "plans",
  BILLING_HISTORY: "billingHistory",
  BILLING_FILTER_OPTIONS: "billingFilterOptions",
  FOLDERS: "folders",
};
